In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [5]:
data=pd.read_csv("1.02.+Multiple+linear+regression.csv")

In [7]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [ ]:
# data.describe()

In [9]:
x=data[["SAT","Rand 1,2,3"]]
y=data["GPA"]

In [10]:
reg=LinearRegression()

In [11]:
reg.fit(x,y)

LinearRegression()

In [12]:
reg.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

In [14]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [15]:
reg.score(x,y)
#R-squared

0.40668119528142843

# Feature Selection

In [16]:
from sklearn.feature_selection import f_regression

In [17]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [18]:
p_values=f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [20]:
p_values.round(3)

array([0.   , 0.676])

# Creating a Summary Table

In [23]:
reg_summary=pd.DataFrame(data=x.columns.values,columns=["Features"])

reg_summary ["Coefficients"]=reg.coef_
reg_summary ["p-values"]=p_values.round(3)

In [24]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676